apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision:  {{ .Values.spec.prometheus.helmchartVersion }}
      chart: prometheus
      helm:
        valueFiles:
        - {{ printf "$values/clusters/%s/utilities/values/prometheus-values.yaml" .Values.spec.cluster | quote }}
    - repoURL: 'https://github.com/daseth/gitops.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
