apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
      targetRevision:  {{ .Values.spec.sealedSecrets.helmchartVersion }}
      chart: sealed-secrets
      helm:
        valueFiles:
        - {{ printf "$values/clusters/%s/utilities/values/sealed-secrets-values.yaml" .Values.spec.cluster | quote }}
    - repoURL: 'https://github.com/daseth/gitops.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true